### ISSUE TITLE
Incorrect wordpiece vocabulary being used for pre-training

### ISSUE THREAD

**Issue by achyudh** [omniocular/omniocular#29]
The vocab file being used (https://github.com/omniocular/omniocular/blob/master/util/tokenization.py) corresponds to natural language and not code. This would have to be replaced with the corresponding vocab files trained for individual programming languages using [SentencePeice](https://github.com/google/sentencepiece). Ideally, we would have a cased and uncased vocabulary in order to experiment with both and see what works.

**Comment by ji-xin** [comment]
Solved
